apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rings.rings.microsoft.com
spec:
  group: rings.microsoft.com
  names:
    kind: Ring
    listKind: RingList
    plural: rings
    singular: ring
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            deploy:
              description: Deploy marks whether this ring will be deployed to the
                live environment
              type: boolean
            routing:
              description: Routing describes the service, group and users to be included
                in the ring
              properties:
                branch:
                  description: Branch will target the deployments with this branch
                    tag
                  type: string
                group:
                  description: The target group of the ring
                  properties:
                    initialUsers:
                      description: The initial users to be included in the group
                      items:
                        type: string
                      type: array
                    name:
                      description: The name of the group to be included in the ring
                      type: string
                  required:
                  - name
                  type: object
                ports:
                  description: Ports will expose these ports on the services and verified
                    against the Deployment found
                  items:
                    properties:
                      name:
                        description: The name of this port within the service. This
                          must be a DNS_LABEL. All ports within a ServiceSpec must
                          have unique names. This maps to the 'Name' field in EndpointPort
                          objects. Optional if only one ServicePort is defined on
                          this service.
                        type: string
                      port:
                        description: The port that will be exposed by this service.
                        format: int32
                        type: integer
                      protocol:
                        description: The IP protocol for this port. Supports "TCP",
                          "UDP", and "SCTP". Default is TCP.
                        type: string
                      targetPort:
                        anyOf:
                        - type: string
                        - type: integer
                        description: 'Number or name of the port to access on the
                          pods targeted by the service. Number must be in the range
                          1 to 65535. Name must be an IANA_SVC_NAME. If this is a
                          string, it will be looked up as a named port in the target
                          Pod''s container ports. If this is not specified, the value
                          of the ''port'' field is used (an identity map). This field
                          is ignored for services with clusterIP=None, and should
                          be omitted or set equal to the ''port'' field. More info:
                          https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service'
                    required:
                    - port
                    type: object
                  type: array
                service:
                  description: Service will target the deployments with this service
                    tag
                  type: string
                version:
                  description: Version will target the deployments with this major
                    version tag
                  type: string
              required:
              - group
              - service
              - version
              - branch
              - ports
              type: object
          required:
          - deploy
          - routing
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
