apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8000
    - protocol: TCP
      name: https
      port: 4443
    - protocol: TCP
      name: internal
      port: 8010
    - protocol: TCP
      name: admin
      port: 8080
  type: LoadBalancer
  selector:
    app: traefik